---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-postgres-pv
  namespace: gitlab
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.71.9.51
    path: /gitlab/gitlab-postgres-pv
  persistentVolumeReclaimPolicy: Recycle
